# Generated by Django 4.2.5 on 2023-09-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=50)),
                ('private_key', models.CharField(max_length=64)),
            ],
        ),
    ]
